spring:
  profiles:
    active: dev
  application:
    bane: link-shortener
  datasource:
    url: jdbc:postgresql://localhost:5433/link-shortener
    username: postgres
    password: 123456
    hikari:
      schema: link_shortener
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace



link-shortener:
  system-id: ${spring.application.name}
  short-link-length: 8
  enable-log-exec-time: false
